//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KobiDataFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Emails = new HashSet<Email>();
        }
    
        public int Id { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public System.DateTime Birthdate { get; set; }
    
        public virtual ICollection<Email> Emails { get; set; }
    }
}
